# This is a basic workflow to help you get started with Actions

name: Build OpenSim and Godot
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  Build:
    name: Build OpenSim and Godot
    runs-on: ubuntu-22.04

    steps:
      - name: download OpenSim installation script
        run: wget https://github.com/opensim-org/opensim-core/blob/main/scripts/build/opensim-core-linux-build-script.sh

      - name: run installation script in Release configuration type, with one thread, and without Moco
        run: |
          sudo chmod +x opensim-core-linux-build-script.sh
          ./opensim-core-linux-build-script.sh -dRelease -j1 -s

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ SECRETS.PAT_submodules }}
          
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Installs SCons
      - name: Install SCons
        run: python -m pip install scons

      - name: Run SCons to build Godot Engine
        run: |
          cd submodules/godot/
          scons shared_library=no vsproj=no platform=linuxbsd target=editor custom_modules=../godosim-cpp-modules

      - name: Create directory for artifact
        run: mkdir -p build-report/
      
      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: build-report/report.txt
          retention-days: 10
